twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        cats: '@App\Twig\CatsExtension'
        search: '@App\Twig\SearchExtension'


when@test:
    twig:
        strict_variables: true
