#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml
# app_categories_menu_burger:
#     path: /categories/menu-burger
#     controller: App\Controller\CategoriesController::menuBurger
